const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

const MESSAGES = {
  SUCCESS: {
    CATEGORY_ADDED: "Category added successfully",
    OFFER_REMOVED: "offer removed successfully",
    COUPON_CREATED: "Coupon created successfully",
    COUPON_STATUS_UPDATED: "Coupon status updated successfully",
    COUPON_UPDATED: "Coupon updated successfully",
    ITEM_CANCELLED: "Item cancelled successfully",
    ITEM_STATUS_UPDATED: "Item status updated successfully",
    RETURN_APPROVED: "Return approved successfully",
    RETURN_REJECTED: "Return request rejected successfully",
  },
  ERROR: {
    INVALID_CREDENTIALS: "Invalid email or password",
    GENERAL_ERROR: "An error occurred. Please try again later.",
    SESSION_DESTROY_ERROR: "Error destroying session",
    LOGOUT_ERROR: "An error occured",
    INTERNAL_SERVER_ERROR: "Internal server error",
    NO_BRAND_FOUND: "no brand found",
    INTERNAL_SERVER_ERROR_LOWER: "internal server error",
    REQUIRED_FIELDS: "name and description are required",
    CATEGORY_EXISTS: "Category already exists",
    SERVER_ERROR: "server error",
    CATEGORY_NOT_FOUND: "category not found",
    PRODUCT_OFFER_EXISTS:
      "products within this category already has product offer",
    SERVER_ERROR_CAPS: "Server error",
    CATEGORY_NOT_FOUND_EDIT: "category not found",
    CATEGORY_EXISTS_EDIT: "Category exists, please choose another name",
    COUPON_EXISTS: "Coupon already exists",
    COUPON_NOT_FOUND: "Coupon not found",
    ADDRESS_NOT_FOUND: "Address Not Found",
    INVALID_DOWNLOAD_TYPE: "Invalid download type",
    INVALID_PERIOD: "Invalid period",
    ORDER_NOT_FOUND: "Order not found",
    ITEM_NOT_FOUND: "Item not found in order",
    ITEM_ALREADY_CANCELLED: "Item is already cancelled",
    CANNOT_CANCEL_DELIVERED: "Cannot cancel delivered item",
    INVALID_STATUS: "Invalid status",
    NOT_PENDING_RETURN: "This order is not pending return approval",
    ITEM_NOT_PENDING_RETURN: "This item is not pending return approval",
    INVALID_CATEGORY_NAME: "Invalid category name",
    INVALID_BRAND_NAME: "Invalid brand name",
    PRODUCT_EXISTS: "product already exists",
    CANNOT_FETCH_PRODUCTS: "cannot fetch products",
    CATEGORY_OFFER_EXISTS: "This product already has category offer applied",
  },
};

module.exports = {
  STATUS_CODES,
  MESSAGES,
};
