const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

const MESSAGES = {
  SUCCESS: {
    CATEGORY_ADDED: "Category added successfully",
    OFFER_REMOVED: "offer removed successfully",
    COUPON_CREATED: "Coupon created successfully",
    COUPON_STATUS_UPDATED: "Coupon status updated successfully",
    COUPON_UPDATED: "Coupon updated successfully",
    ITEM_CANCELLED: "Item cancelled successfully",
    ITEM_STATUS_UPDATED: "Item status updated successfully",
    RETURN_APPROVED: "Return approved successfully",
    RETURN_REJECTED: "Return request rejected successfully",
    ITEM_ADDED_TO_CART: "Item added to cart successfully",
    CART_UPDATED: "Cart updated successfully",
    RETURN_REQUEST_SUBMITTED: "Return request submitted successfully",
    COUPON_REMOVED: "Coupon removed successfully",
    OTP_SENT: "OTP Resent!",
    PASSWORD_CHANGED: "Password changed successfully",
  },
  ERROR: {
    INVALID_CREDENTIALS: "Invalid email or password",
    GENERAL_ERROR: "An error occurred. Please try again later.",
    SESSION_DESTROY_ERROR: "Error destroying session",
    LOGOUT_ERROR: "An error occured",
    INTERNAL_SERVER_ERROR: "Internal server error",
    NO_BRAND_FOUND: "no brand found",
    INTERNAL_SERVER_ERROR_LOWER: "internal server error",
    REQUIRED_FIELDS: "name and description are required",
    CATEGORY_EXISTS: "Category already exists",
    SERVER_ERROR: "server error",
    CATEGORY_NOT_FOUND: "category not found",
    PRODUCT_OFFER_EXISTS:
      "products within this category already has product offer",
    SERVER_ERROR_CAPS: "Server error",
    CATEGORY_NOT_FOUND_EDIT: "category not found",
    CATEGORY_EXISTS_EDIT: "Category exists, please choose another name",
    COUPON_EXISTS: "Coupon already exists",
    COUPON_NOT_FOUND: "Coupon not found",
    ADDRESS_NOT_FOUND: "Address Not Found",
    INVALID_DOWNLOAD_TYPE: "Invalid download type",
    INVALID_PERIOD: "Invalid period",
    ORDER_NOT_FOUND: "Order not found",
    ITEM_NOT_FOUND: "Item not found in order",
    ITEM_ALREADY_CANCELLED: "Item is already cancelled",
    CANNOT_CANCEL_DELIVERED: "Cannot cancel delivered item",
    INVALID_STATUS: "Invalid status",
    NOT_PENDING_RETURN: "This order is not pending return approval",
    ITEM_NOT_PENDING_RETURN: "This item is not pending return approval",
    INVALID_CATEGORY_NAME: "Invalid category name",
    INVALID_BRAND_NAME: "Invalid brand name",
    PRODUCT_EXISTS: "product already exists",
    CANNOT_FETCH_PRODUCTS: "cannot fetch products",
    CATEGORY_OFFER_EXISTS: "This product already has category offer applied",
    SIZE_REQUIRED: "Size is required",
    PRODUCT_NOT_FOUND: "Product not found",
    NOT_ENOUGH_STOCK: "Not enough stock for selected size",
    UNEXPECTED_ERROR: "An unexpected error occurred",
    CART_NOT_FOUND: "Cart not found",
    ERROR_FETCHING_CART: "Error fetching cart",
    ERROR_REMOVING_FROM_CART: "Error removing from cart",
    ERROR_UPDATING_CART: "Error updating cart",
    ERROR_CALCULATING_CART_TOTAL: "Error calculating cart total",
    ITEM_NOT_FOUND_IN_CART: "Item not found in cart",
    CANNOT_CANCEL_ORDER: "Cannot cancel this order",
    ITEM_ALREADY_CANCELLED: "Item is already cancelled",
    CANNOT_CANCEL_DELIVERED_ITEM: "Cannot cancel delivered item",
    ITEM_CANNOT_BE_RETURNED: "Item cannot be returned unless delivered",
    ORDER_CANNOT_BE_RETURNED: "Order cannot be returned unless delivered",
    CART_EMPTY: "Cart is empty",
    COUPON_ALREADY_USED: "You have already used this coupon",
    COUPON_INVALID: "Coupon is not valid",
    ADDRESS_REQUIRED: "Address is required",
    COD_LIMIT_EXCEEDED: "COD is not available for orders above Rs 1000",
    PAYMENT_METHOD_REQUIRED: "payment method is required",
    PRODUCT_BLOCKED: "Product is blocked and cannot be ordered",
    ADDRESS_SELECTION_REQUIRED:
      "Please select an existing address or add a new one",
    INSUFFICIENT_WALLET_BALANCE: "Insufficient wallet balance",
    INVALID_PAYMENT_METHOD: "Invalid payment method",
    CHECKOUT_SESSION_NOT_FOUND: "Checkout session not found",
    PAYMENT_ERROR: "An error occurred",
    INVALID_ORDER_PAYMENT: "Invalid order or payment already completed",
    PAYMENT_INITIATION_ERROR: "error initiating payment",
    INSUFFICIENT_QUANTITY: "is out of stock or has insufficient quantity",
    PRODUCT_OUT_OF_STOCK: "not found",
    ERROR_REMOVING_COUPON: "Error removing coupon:",
    PAYMENT_INITIATION_FAILED: "failed to initiate payment",
    FAILED_TO_SEND_OTP: "failed to send otp",
    USER_NOT_EXISTS: "User with this email does not exist",
    OTP_NOT_MATCH: "OTP does not match",
    AN_ERROR_OCCURRED: "An error occured",
    PASSWORDS_NOT_MATCH: "passwords do not match",
    USER_NOT_FOUND: "User not found",
    ERROR_FETCHING_USER_PROFILE: "error fetching user profile",
    ERROR_UPDATING_PROFILE: "Error updating profile details",
    ALL_FIELDS_REQUIRED: "All fields are required.",
    PASSWORD_MIN_LENGTH: "New password must be atleast 8 characters long",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match",
    INCORRECT_CURRENT_PASSWORD: "Incorrect current password",
  },
};

module.exports = {
  STATUS_CODES,
  MESSAGES,
};
